#!/bin/bash -noprofile
##
## @package phosim_gui
## @file phosim_gui
## @brief script to run phosim GUI python tool
##
## @brief Created by:
## @author John R. Peterson (Purdue)
##
## @brief Modified by:
##
## @warning This code is not fully validated
## and not ready for full release.  Please
## treat results with caution.
##
. bin/setup
${PYTHON} tools/phosim_gui.py $@
