#!/usr/bin/env python

"""
  @package phosim
  @file ClestronEdgeHDDispersion.py
  @brief python script to generate the dispersion files for the 4 glasses
  @used in lenses for the CeletronEdgeHD telescopes
  
  @brief Created by:
  @author Glenn Sembroski (Purdue)
 
  @warning This code is not fully validated
  and not ready for full release.  Please
  treat results with caution.

# Script to generate the dispersion files (wavelength vs Index of refratcion)
# files for the CelestronEdgeHD telescopes (8, 9.25, 11, 14 inch apertures).
# Use the  Sellmeier dispersion formula and constants for the 4 lens
# materials. see:
# https://refractiveindex.info/download/data/2017/schott_2017-01-20.pdf
#NOTE THAT WHILE ITS NOT STATED EXPLICTLY, LAMDA IS IN MICROMMETERS IN THE
#SELLMETER EQUATION for the B1,B2,B3,C1,C2 and C3 constants given in that
#reference.

# Lens types generated by this script: N-BK7,  N-SK2. K10 and N-BALF4.
# Constants for other glasses are avable at the same source. 
"""
import sys
import os
import math


def SellmeierDispersion(GlassConstantsList,WavelengthStartNM, WavelengthLastNM,
                        WavelengthStepSizeNM ) :
    #rename list elements for clarity to match the above reference
    B1=GlassConstantsList[0]
    B2=GlassConstantsList[1]
    B3=GlassConstantsList[2]
    C1=GlassConstantsList[3]
    C2=GlassConstantsList[4]
    C3=GlassConstantsList[5]
    #print('B1:' + str(B1) + '\n')
    #print('C1c1:' + str(C1) + '\n')
    
    DispersionList = []   #initalize list that we will append to.
    WavelengthSteps = int(( WavelengthLastNM-WavelengthStartNM ) /
                        WavelengthStepSizeNM ) + 1
    #print(str(WavelengthSteps) + '\n')
    for m in range(0,WavelengthSteps) :
        LambdaNM = WavelengthStartNM  +  (m * WavelengthStepSizeNM)
        Lambda = LambdaNM/1000.  #Need Lambda in mirometers, see above.
        LambdaSqr = Lambda * Lambda
        a1 =      ( (B1*LambdaSqr)/(LambdaSqr-C1) )
        a2 =      ( (B2*LambdaSqr)/(LambdaSqr-C2) )
        a3 =      ( (B3*LambdaSqr)/(LambdaSqr-C3) )
        n2 = a1 + a2 + a3 + 1.0
        n=math.sqrt(n2)
        #print ('Lambda,LambdaSqr,a1,a2,a3,n2,n:' + str(Lambda) + ', ' \
        #       + str(LambdaSqr) + ', ' \
        #       + str(a1) + ', ' \
        #       + str(a2) + ', ' \
        #       + str(a3) + ', ' \
        #        + str(a1+a2+a3) + ', ' \
        #       + str(n2) + ', ' \
        #       + str(n)  )
        #exit()
        dispersionEntry = [ Lambda, n ]  #a list for a single wavelength

        #add to dispersion list
        #print(str(dispersionEntry))
        if m == 0 :
            DispersionList = [dispersionEntry]
        else :
            DispersionList.append(dispersionEntry) # A list of lists
    return DispersionList

def SaveDispersionToFile(FileName, DispersionList) :
    dispersionFile = open(FileName,"w")
    #print(FileName + ":" + '\n')
    for dispersionEntry in DispersionList :
        #print(str(dispersionEntry))
        Lambda = dispersionEntry[0]
        #print( 'Lambda:' + str(Lambda) + '\n')
        indexOfRefraction = dispersionEntry[1]
        entryString = '       ' + str( float(Lambda) ) + '       ' + \
                   str( float(indexOfRefraction) ) + '\n'
        #print(entryString)

        dispersionFile.write(entryString)

    dispersionFile.close()
    return

##################################################
#Main program
##################################################

#Setup constants for the 4 glass types:
# dispersionConstants=[B1,B2.B3.C1,C2,C3]

def main():
    N_BK7 = [	1.03961212, 0.231792344, 1.01046945, \
                0.00600069867, 0.0200179144, 103.560653 ]

    N_SK2 = [ 1.28189012, 0.257738258, 0.96818604, \
              0.0072719164, 0.0242823527,110.377773 ]

    K10   = [ 1.15687082, 0.0642625444, 0.872376139, \
              0.00809424251, 0.0386051284, 104.74773 ]

    N_BALF4 = [ 1.31004128, 0.142038259, 0.964929351, \
                0.0079659645, 0.0330672072, 109.19732 ]

    # Generate the files
   
    BK7DispersionList =SellmeierDispersion( N_BK7,  300.0, 1530.0, 1.0 )
    #print(str(BK7DispersionList))
    SaveDispersionToFile("N_BK7.txt", BK7DispersionList) 

    SK2DispersionList = SellmeierDispersion( N_SK2,  300.0, 1530.0, 1.0 )
    SaveDispersionToFile("N_SK2.txt",SK2DispersionList)

    K10DispersionList = SellmeierDispersion( K10,  300.0, 1530.0, 1.0 )
    SaveDispersionToFile("K10.txt", K10DispersionList)

    BALF4DispersionList = SellmeierDispersion(N_BALF4,  300.0, 1530.0, 1.0)
    SaveDispersionToFile("N_BALF4.txt", BALF4DispersionList)



if __name__=='__main__':
    main()
